In [1]:
pip install mosqlient

Requirement already satisfied: mosqlient in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (2.5.2)
Requirement already satisfied: aiohttp<4.0.0,>=3.9.5 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from mosqlient) (3.14.1)
Requirement already satisfied: cffi<2.0.0,>=1.17.0 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from mosqlient) (1.17.1)
Requirement already satisfied: epiweeks<3.0.0,>=2.3.0 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from mosqlient) (2.4.0)
Requirement already satisfied: loguru<0.8.0,>=0.7.3 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from mosqlient) (0.7.3)
Requirement already satisfied: nest-asyncio<2.0.0,>=1.6.0 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from mosqlient) (1.6.0)
Requirement already satisfied: numpy>=2.2.5 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from mosqlient) (2.5.0)
Requirement already satisfied: pandas<3.0.0,>=2.2.2 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from mosqlient) (2.3.3)
Requirement already satisfied: pydantic<3.0.0,>=2.7.3 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from mosqlient) (2.13.4)
Requirement already satisfied: requests<3.0.0,>=2.32.2 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from mosqlient) (2.34.2)
Requirement already satisfied: seaborn<0.14.0,>=0.13.2 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from mosqlient) (0.13.2)
Requirement already satisfied: tabulate<0.10.0,>=0.9.0 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from mosqlient) (0.9.0)
Requirement already satisfied: tqdm<5.0.0,>=4.67.1 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from mosqlient) (4.68.3)
Requirement already satisfied: types-requests<3.0.0.0,>=2.32.0.20240523 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from mosqlient) (2.33.0.20260518)
Requirement already satisfied: vl-convert-python<2.0.0,>=1.7.0 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from mosqlient) (1.9.0.post1)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from aiohttp<4.0.0,>=3.9.5->mosqlient) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from aiohttp<4.0.0,>=3.9.5->mosqlient) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from aiohttp<4.0.0,>=3.9.5->mosqlient) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from aiohttp<4.0.0,>=3.9.5->mosqlient) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from aiohttp<4.0.0,>=3.9.5->mosqlient) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from aiohttp<4.0.0,>=3.9.5->mosqlient) (0.5.2)
Requirement already satisfied: typing_extensions>=4.4 in c:\users\marcela.motta\appdata\roaming\python\python312\site-packages (from aiohttp<4.0.0,>=3.9.5->mosqlient) (4.15.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from aiohttp<4.0.0,>=3.9.5->mosqlient) (1.24.2)
Requirement already satisfied: pycparser in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from cffi<2.0.0,>=1.17.0->mosqlient) (3.0)
Requirement already satisfied: colorama>=0.3.4 in c:\users\marcela.motta\appdata\roaming\python\python312\site-packages (from loguru<0.8.0,>=0.7.3->mosqlient) (0.4.6)
Requirement already satisfied: win32-setctime>=1.0.0 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from loguru<0.8.0,>=0.7.3->mosqlient) (1.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\marcela.motta\appdata\roaming\python\python312\site-packages (from pandas<3.0.0,>=2.2.2->mosqlient) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from pandas<3.0.0,>=2.2.2->mosqlient) (2026.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from pandas<3.0.0,>=2.2.2->mosqlient) (2026.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from pydantic<3.0.0,>=2.7.3->mosqlient) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from pydantic<3.0.0,>=2.7.3->mosqlient) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from pydantic<3.0.0,>=2.7.3->mosqlient) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from requests<3.0.0,>=2.32.2->mosqlient) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from requests<3.0.0,>=2.32.2->mosqlient) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from requests<3.0.0,>=2.32.2->mosqlient) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from requests<3.0.0,>=2.32.2->mosqlient) (2026.6.17)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from seaborn<0.14.0,>=0.13.2->mosqlient) (3.11.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn<0.14.0,>=0.13.2->mosqlient) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn<0.14.0,>=0.13.2->mosqlient) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn<0.14.0,>=0.13.2->mosqlient) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn<0.14.0,>=0.13.2->mosqlient) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\marcela.motta\appdata\roaming\python\python312\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn<0.14.0,>=0.13.2->mosqlient) (26.2)
Requirement already satisfied: pillow>=9 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn<0.14.0,>=0.13.2->mosqlient) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn<0.14.0,>=0.13.2->mosqlient) (3.3.2)
Requirement already satisfied: six>=1.5 in c:\users\marcela.motta\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas<3.0.0,>=2.2.2->mosqlient) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
pip install python-dotenv

Requirement already satisfied: python-dotenv in c:\users\marcela.motta\appdata\local\programs\python\python312\lib\site-packages (1.2.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import pandas as pd
from mosqlient import upload_prediction

In [ ]:
import mosqlient
print(mosqlient.__version__)

2.5.2

In [14]:
import sys
print(sys.version)

3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]

In [15]:
print(api_key)

researchcenterafya:403c97fa-67c4-49d4-9fe5-32acdae67bb0

In [4]:
import os
from dotenv import load_dotenv

In [5]:
load_dotenv('../Demo Notebooks/.env')

api_key = os.getenv('API_KEY')

In [6]:
prediction_all = pd.read_csv('../src/2_model/predictions.csv')
prediction_all.head()

,split,uf,date,casos_real,lower_95,lower_90,lower_80,lower_50,pred,upper_50,upper_80,upper_90,upper_95
0,1,AC,2022-10-09,31,0.000000,0.000000,2.716262,30.157305,54.21307,89.29031,120.22463,133.74142,139.21107
1,1,AC,2022-10-16,38,14.469205,28.632607,40.293163,62.227665,89.87433,112.51698,141.50285,156.95297,169.83377
2,1,AC,2022-10-23,43,64.024720,71.208010,83.053925,101.353870,125.83045,152.43654,172.03600,189.93086,201.34988
3,1,AC,2022-10-30,35,75.836685,91.703804,110.695980,135.996170,165.09291,196.54213,218.03484,224.63123,227.06348
4,1,AC,2022-11-06,40,90.552820,98.444930,108.082600,136.513610,166.97636,192.10342,213.07050,228.69430,243.44300

In [7]:
prediction = prediction_all[(prediction_all['uf'] == 'RJ') & (prediction_all['split'] == 1)][['date', 'pred', 'lower_50', 'upper_50', 'lower_80', 'upper_80', 'lower_90', 'upper_90', 'lower_95', 'upper_95']]
prediction

,date,pred,lower_50,upper_50,lower_80,upper_80,lower_90,upper_90,lower_95,upper_95
884,2022-10-09,591.17970,399.76420,796.54630,183.12064,978.28326,54.871075,1073.90090,0.000000,1118.2528
885,2022-10-16,576.69020,422.80725,766.95825,228.52486,963.51830,164.282680,1046.37210,100.789180,1177.2545
886,2022-10-23,572.36584,364.35556,750.00696,143.02370,923.83606,70.897900,1002.83460,0.000000,1119.2977
887,2022-10-30,583.03265,463.23690,741.76355,319.65790,896.98610,219.388320,1014.28394,67.167610,1102.5906
888,2022-11-06,618.64087,413.40652,816.77530,223.27708,991.32635,150.699160,1058.68600,29.018723,1158.9980
889,2022-11-13,653.49880,438.32830,823.72420,302.05480,997.92650,235.117310,1170.92240,196.939790,1257.0876
890,2022-11-20,685.29456,456.30853,996.50260,314.13280,1193.00300,202.993500,1271.35550,73.518850,1350.1460
891,2022-11-27,821.02325,594.16235,1085.77300,399.76105,1292.11490,304.951320,1447.59740,224.722470,1565.3566
892,2022-12-04,933.20830,697.95105,1219.91490,500.55124,1483.71830,410.999150,1604.00670,245.739750,1767.8921
893,2022-12-11,1114.25740,826.81390,1477.92040,569.57416,1721.47510,401.970550,1891.88890,345.942840,2068.2246
894,2022-12-18,1347.73690,1033.24460,1692.56150,737.18250,2145.23240,593.090000,2264.87100,373.367770,2475.9658
895,2022-12-25,1461.93300,1181.15050,1875.58390,884.31920,2240.36130,727.283750,2372.26700,563.326840,2521.1904
896,2023-01-01,1501.55940,1189.61950,1929.19380,933.38666,2437.91330,791.263600,2669.63010,617.586400,2851.4978
897,2023-01-08,1565.29110,1219.86100,2064.46220,908.12920,2418.95040,682.634300,2754.50900,410.940430,3205.0840
898,2023-01-15,1667.49460,1245.42210,2138.67070,896.71497,2670.42940,700.420960,3052.94820,428.191740,3293.8914
899,2023-01-22,1720.30970,1296.20760,2183.15110,999.66736,2702.03200,804.106900,2965.02320,419.749150,3376.2676
900,2023-01-29,1769.33600,1322.63840,2250.00050,897.89453,2866.71880,641.511600,3301.02470,461.389740,3439.5190
901,2023-02-05,1766.36760,1304.44460,2256.72530,901.46370,2851.24020,632.323100,3213.61100,451.938350,3545.3552
902,2023-02-12,1682.68920,1149.44250,2233.19340,872.10815,2903.65820,664.937870,3372.49830,298.748630,3586.2220
903,2023-02-19,1566.02540,1122.74550,2138.05030,763.01160,2736.76500,391.716200,3227.79030,121.590195,3722.1460
904,2023-02-26,1565.04600,968.15344,2232.81180,551.14840,2636.50320,359.703100,3245.25340,151.797030,3826.6064
905,2023-03-05,1479.86880,917.79120,1985.63060,477.71738,2786.98560,195.834520,3056.64650,0.000000,3268.9380
906,2023-03-12,1245.87240,753.41534,1804.41200,381.05048,2433.97500,137.299710,2775.05320,0.000000,3088.3735
907,2023-03-19,1141.41710,676.05786,1725.64180,276.76850,2168.87770,45.303356,2512.40900,0.000000,3093.8496
908,2023-03-26,1009.34120,617.82660,1520.82630,245.47162,2061.23200,27.112844,2305.78660,0.000000,2785.0627
909,2023-04-02,971.51720,531.94135,1451.27390,200.81233,1909.59300,64.272900,2231.51170,0.000000,2622.5510
910,2023-04-09,783.86540,486.58612,1183.67040,221.11806,1717.59400,0.000000,2118.24220,0.000000,2512.1475
911,2023-04-16,764.58215,421.06723,1112.07080,97.30750,1564.40990,0.000000,1711.66860,0.000000,2158.8762
912,2023-04-23,770.00690,410.20090,1162.78990,91.64053,1412.13460,0.000000,1699.12740,0.000000,2025.4221
913,2023-04-30,730.51500,451.32986,1115.27430,169.05852,1437.26170,0.000000,1703.33260,0.000000,2020.3042
914,2023-05-07,814.96320,514.18616,1155.33860,136.25580,1382.27580,0.000000,1625.08480,0.000000,1727.2777
915,2023-05-14,913.61470,552.69507,1243.36340,235.37607,1501.15310,85.865036,1769.07350,0.000000,1952.2737
916,2023-05-21,990.02924,648.14800,1279.23850,441.00120,1529.30050,314.160580,1650.69150,242.754930,1797.0393
917,2023-05-28,1015.69965,692.62310,1282.96640,443.03450,1594.26330,351.222840,1709.36660,260.061500,1846.8478
918,2023-06-04,1053.66370,717.44880,1334.86710,497.10052,1525.68970,304.829620,1663.99410,263.085880,1829.3452
919,2023-06-11,1014.92640,800.31134,1297.81310,593.65814,1541.02900,471.797500,1659.91860,406.286530,1825.5164
920,2023-06-18,1071.06950,830.53436,1317.24490,628.27670,1501.55880,462.921700,1691.77750,290.961820,1936.1006
921,2023-06-25,1005.21783,769.65750,1264.04130,566.57900,1452.68380,396.433930,1657.06250,240.858600,1786.5259
922,2023-07-02,959.88245,682.99567,1219.94240,483.22995,1443.20980,326.941250,1541.63620,296.350280,1636.8275
923,2023-07-09,907.39410,703.20610,1185.17550,436.01380,1334.80080,325.312800,1464.17690,251.416210,1493.1671
924,2023-07-16,803.02814,592.23870,1034.33720,402.39703,1209.65670,313.414100,1361.46350,241.386050,1574.7827
925,2023-07-23,774.68160,552.79584,1028.11790,353.00037,1200.09510,251.131160,1312.98250,169.569670,1412.6125
926,2023-07-30,762.77420,525.01843,981.16650,294.27972,1239.20450,209.757310,1402.71810,174.888570,1573.0043
927,2023-08-06,730.35614,520.67610,992.67926,369.09988,1161.68920,290.324860,1321.04800,196.095860,1493.4042
928,2023-08-13,797.47010,533.35614,1024.45750,269.05432,1196.17070,190.719590,1304.84810,136.709660,1502.0564
929,2023-08-20,746.59440,544.24854,933.18677,322.81555,1179.04830,212.830180,1295.05770,186.285060,1522.2255
930,2023-08-27,745.14520,470.65960,951.66565,264.77140,1118.03090,184.395800,1224.27860,80.599240,1255.0901
931,2023-09-03,624.12555,410.64530,831.96960,244.96191,987.80035,153.363530,1155.17030,34.603270,1313.5898
932,2023-09-10,661.31240,493.50455,866.79730,275.69235,1065.33750,202.074690,1163.05430,82.295970,1303.1088
933,2023-09-17,669.71620,471.89010,878.95220,336.56308,1127.26810,231.507610,1304.31300,167.646400,1358.7543
934,2023-09-24,763.93690,539.30830,950.96540,385.15237,1117.88480,274.692470,1232.06020,220.607640,1419.0983
935,2023-10-01,829.27020,601.35895,1005.94183,388.20230,1239.04420,317.372100,1405.67880,308.495330,1586.0776

In [8]:
repository = 'Ricafya/3rd_imdc_afya_ric'
description = 'LSTM Model to predict dengue cases in each uf'
commit = '0cfbbc4801bb2a7520bb48d3502563e5cfcb395e'
disease = 'A90'
adm_level = 1
adm_1 = 33
adm_2 = None
case_definition = 'probable'
published = True

In [9]:
res = upload_prediction(
  api_key = api_key,
  repository = repository,
  description = description,
  commit = commit,
  disease = disease,
  case_definition = case_definition,
  adm_level = adm_level,
  adm_1 = adm_1,
  published = published,
  prediction = prediction
)

print(res)

ValueError: {"message": "Duplication found for this Prediction within the Model"}